// Code generated by Thrift Compiler (0.22.0). DO NOT EDIT.

package gift_service

import (
	"bytes"
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"log/slog"
	"regexp"
	"strings"
	"time"

	thrift "github.com/apache/thrift/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = bytes.Equal
var _ = context.Background
var _ = errors.New
var _ = fmt.Printf
var _ = iter.Pull[int]
var _ = slog.Log
var _ = time.Now
var _ = thrift.ZERO

// (needed by validator.)
var _ = strings.Contains
var _ = regexp.MatchString

type GiftType int64

const (
	GiftType_GIFT_TYPE_UNKNOWN GiftType = 0
	GiftType_GIFT_TYPE_NORMAL  GiftType = 1
	GiftType_GIFT_TYPE_SPECIAL GiftType = 2
)

var knownGiftTypeValues = []GiftType{
	GiftType_GIFT_TYPE_UNKNOWN,
	GiftType_GIFT_TYPE_NORMAL,
	GiftType_GIFT_TYPE_SPECIAL,
}

func GiftTypeValues() iter.Seq[GiftType] {
	return func(yield func(GiftType) bool) {
		for _, v := range knownGiftTypeValues {
			if !yield(v) {
				return
			}
		}
	}
}

func (p GiftType) String() string {
	switch p {
	case GiftType_GIFT_TYPE_UNKNOWN:
		return "GIFT_TYPE_UNKNOWN"
	case GiftType_GIFT_TYPE_NORMAL:
		return "GIFT_TYPE_NORMAL"
	case GiftType_GIFT_TYPE_SPECIAL:
		return "GIFT_TYPE_SPECIAL"
	}
	return "<UNSET>"
}

func GiftTypeFromString(s string) (GiftType, error) {
	switch s {
	case "GIFT_TYPE_UNKNOWN":
		return GiftType_GIFT_TYPE_UNKNOWN, nil
	case "GIFT_TYPE_NORMAL":
		return GiftType_GIFT_TYPE_NORMAL, nil
	case "GIFT_TYPE_SPECIAL":
		return GiftType_GIFT_TYPE_SPECIAL, nil
	}
	return GiftType(0), fmt.Errorf("not a valid GiftType string")
}

func GiftTypePtr(v GiftType) *GiftType { return &v }

func (p GiftType) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *GiftType) UnmarshalText(text []byte) error {
	q, err := GiftTypeFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *GiftType) Scan(value interface{}) error {
	v, ok := value.(int64)
	if !ok {
		return errors.New("Scan value is not int64")
	}
	*p = GiftType(v)
	return nil
}

func (p *GiftType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

// Attributes:
//   - GiftId
//   - SenderId
//   - ReceiverId
//   - Price
//   - GiftType
//   - Quantity
//   - SendTime
type Gift struct {
	GiftId     int64    `thrift:"giftId,1" db:"giftId" json:"giftId"`
	SenderId   int64    `thrift:"senderId,2" db:"senderId" json:"senderId"`
	ReceiverId int64    `thrift:"receiverId,3" db:"receiverId" json:"receiverId"`
	Price      int32    `thrift:"price,4" db:"price" json:"price"`
	GiftType   GiftType `thrift:"giftType,5" db:"giftType" json:"giftType"`
	Quantity   int32    `thrift:"quantity,6" db:"quantity" json:"quantity"`
	SendTime   int64    `thrift:"sendTime,7" db:"sendTime" json:"sendTime"`
}

func NewGift() *Gift {
	return &Gift{}
}

func (p *Gift) GetGiftId() int64 {
	return p.GiftId
}

func (p *Gift) GetSenderId() int64 {
	return p.SenderId
}

func (p *Gift) GetReceiverId() int64 {
	return p.ReceiverId
}

func (p *Gift) GetPrice() int32 {
	return p.Price
}

func (p *Gift) GetGiftType() GiftType {
	return p.GiftType
}

func (p *Gift) GetQuantity() int32 {
	return p.Quantity
}

func (p *Gift) GetSendTime() int64 {
	return p.SendTime
}

func (p *Gift) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I64 {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.I64 {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 3:
			if fieldTypeId == thrift.I64 {
				if err := p.ReadField3(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 4:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField4(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 5:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField5(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 6:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField6(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 7:
			if fieldTypeId == thrift.I64 {
				if err := p.ReadField7(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *Gift) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.GiftId = v
	}
	return nil
}

func (p *Gift) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(ctx); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.SenderId = v
	}
	return nil
}

func (p *Gift) ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(ctx); err != nil {
		return thrift.PrependError("error reading field 3: ", err)
	} else {
		p.ReceiverId = v
	}
	return nil
}

func (p *Gift) ReadField4(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 4: ", err)
	} else {
		p.Price = v
	}
	return nil
}

func (p *Gift) ReadField5(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 5: ", err)
	} else {
		temp := GiftType(v)
		p.GiftType = temp
	}
	return nil
}

func (p *Gift) ReadField6(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 6: ", err)
	} else {
		p.Quantity = v
	}
	return nil
}

func (p *Gift) ReadField7(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(ctx); err != nil {
		return thrift.PrependError("error reading field 7: ", err)
	} else {
		p.SendTime = v
	}
	return nil
}

func (p *Gift) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "Gift"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField2(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField3(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField4(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField5(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField6(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField7(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *Gift) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "giftId", thrift.I64, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:giftId: ", p), err)
	}
	if err := oprot.WriteI64(ctx, int64(p.GiftId)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.giftId (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:giftId: ", p), err)
	}
	return err
}

func (p *Gift) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "senderId", thrift.I64, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:senderId: ", p), err)
	}
	if err := oprot.WriteI64(ctx, int64(p.SenderId)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.senderId (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:senderId: ", p), err)
	}
	return err
}

func (p *Gift) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "receiverId", thrift.I64, 3); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:receiverId: ", p), err)
	}
	if err := oprot.WriteI64(ctx, int64(p.ReceiverId)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.receiverId (3) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 3:receiverId: ", p), err)
	}
	return err
}

func (p *Gift) writeField4(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "price", thrift.I32, 4); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:price: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.Price)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.price (4) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 4:price: ", p), err)
	}
	return err
}

func (p *Gift) writeField5(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "giftType", thrift.I32, 5); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 5:giftType: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.GiftType)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.giftType (5) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 5:giftType: ", p), err)
	}
	return err
}

func (p *Gift) writeField6(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "quantity", thrift.I32, 6); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 6:quantity: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.Quantity)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.quantity (6) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 6:quantity: ", p), err)
	}
	return err
}

func (p *Gift) writeField7(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "sendTime", thrift.I64, 7); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 7:sendTime: ", p), err)
	}
	if err := oprot.WriteI64(ctx, int64(p.SendTime)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.sendTime (7) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 7:sendTime: ", p), err)
	}
	return err
}

func (p *Gift) Equals(other *Gift) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if p.GiftId != other.GiftId {
		return false
	}
	if p.SenderId != other.SenderId {
		return false
	}
	if p.ReceiverId != other.ReceiverId {
		return false
	}
	if p.Price != other.Price {
		return false
	}
	if p.GiftType != other.GiftType {
		return false
	}
	if p.Quantity != other.Quantity {
		return false
	}
	if p.SendTime != other.SendTime {
		return false
	}
	return true
}

func (p *Gift) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Gift(%+v)", *p)
}

func (p *Gift) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*gift_service.Gift",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*Gift)(nil)

func (p *Gift) Validate() error {
	return nil
}

type GiftService interface {
	// Parameters:
	//  - SenderId
	//  - ReceiverId
	//  - Price
	//  - GiftType
	//  - Quantity
	//
	SendGift(ctx context.Context, senderId int64, receiverId int64, price int32, giftType GiftType, quantity int32) (_r *Gift, _err error)
	GetTop10Senders(ctx context.Context) (_r []int64, _err error)
	GetSendersInLastWeek(ctx context.Context) (_r []int64, _err error)
	// Parameters:
	//  - SenderId
	//
	GetGiftsBySender(ctx context.Context, senderId int64) (_r []*Gift, _err error)
}

type GiftServiceClient struct {
	c    thrift.TClient
	meta thrift.ResponseMeta
}

func NewGiftServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *GiftServiceClient {
	return &GiftServiceClient{
		c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
	}
}

func NewGiftServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *GiftServiceClient {
	return &GiftServiceClient{
		c: thrift.NewTStandardClient(iprot, oprot),
	}
}

func NewGiftServiceClient(c thrift.TClient) *GiftServiceClient {
	return &GiftServiceClient{
		c: c,
	}
}

func (p *GiftServiceClient) Client_() thrift.TClient {
	return p.c
}

func (p *GiftServiceClient) LastResponseMeta_() thrift.ResponseMeta {
	return p.meta
}

func (p *GiftServiceClient) SetLastResponseMeta_(meta thrift.ResponseMeta) {
	p.meta = meta
}

// Parameters:
//   - SenderId
//   - ReceiverId
//   - Price
//   - GiftType
//   - Quantity
func (p *GiftServiceClient) SendGift(ctx context.Context, senderId int64, receiverId int64, price int32, giftType GiftType, quantity int32) (_r *Gift, _err error) {
	var _args0 GiftServiceSendGiftArgs
	_args0.SenderId = senderId
	_args0.ReceiverId = receiverId
	_args0.Price = price
	_args0.GiftType = giftType
	_args0.Quantity = quantity
	var _result2 GiftServiceSendGiftResult
	var _meta1 thrift.ResponseMeta
	_meta1, _err = p.Client_().Call(ctx, "SendGift", &_args0, &_result2)
	p.SetLastResponseMeta_(_meta1)
	if _err != nil {
		return
	}
	if _ret3 := _result2.GetSuccess(); _ret3 != nil {
		return _ret3, nil
	}
	return nil, thrift.NewTApplicationException(thrift.MISSING_RESULT, "SendGift failed: unknown result")
}

func (p *GiftServiceClient) GetTop10Senders(ctx context.Context) (_r []int64, _err error) {
	var _args4 GiftServiceGetTop10SendersArgs
	var _result6 GiftServiceGetTop10SendersResult
	var _meta5 thrift.ResponseMeta
	_meta5, _err = p.Client_().Call(ctx, "GetTop10Senders", &_args4, &_result6)
	p.SetLastResponseMeta_(_meta5)
	if _err != nil {
		return
	}
	return _result6.GetSuccess(), nil
}

func (p *GiftServiceClient) GetSendersInLastWeek(ctx context.Context) (_r []int64, _err error) {
	var _args7 GiftServiceGetSendersInLastWeekArgs
	var _result9 GiftServiceGetSendersInLastWeekResult
	var _meta8 thrift.ResponseMeta
	_meta8, _err = p.Client_().Call(ctx, "GetSendersInLastWeek", &_args7, &_result9)
	p.SetLastResponseMeta_(_meta8)
	if _err != nil {
		return
	}
	return _result9.GetSuccess(), nil
}

// Parameters:
//   - SenderId
func (p *GiftServiceClient) GetGiftsBySender(ctx context.Context, senderId int64) (_r []*Gift, _err error) {
	var _args10 GiftServiceGetGiftsBySenderArgs
	_args10.SenderId = senderId
	var _result12 GiftServiceGetGiftsBySenderResult
	var _meta11 thrift.ResponseMeta
	_meta11, _err = p.Client_().Call(ctx, "GetGiftsBySender", &_args10, &_result12)
	p.SetLastResponseMeta_(_meta11)
	if _err != nil {
		return
	}
	return _result12.GetSuccess(), nil
}

type GiftServiceProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      GiftService
}

func (p *GiftServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *GiftServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *GiftServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewGiftServiceProcessor(handler GiftService) *GiftServiceProcessor {

	self13 := &GiftServiceProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self13.processorMap["SendGift"] = &giftServiceProcessorSendGift{handler: handler}
	self13.processorMap["GetTop10Senders"] = &giftServiceProcessorGetTop10Senders{handler: handler}
	self13.processorMap["GetSendersInLastWeek"] = &giftServiceProcessorGetSendersInLastWeek{handler: handler}
	self13.processorMap["GetGiftsBySender"] = &giftServiceProcessorGetGiftsBySender{handler: handler}
	return self13
}

func (p *GiftServiceProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err2 := iprot.ReadMessageBegin(ctx)
	if err2 != nil {
		return false, thrift.WrapTException(err2)
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(ctx, seqId, iprot, oprot)
	}
	iprot.Skip(ctx, thrift.STRUCT)
	iprot.ReadMessageEnd(ctx)
	x14 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(ctx, name, thrift.EXCEPTION, seqId)
	x14.Write(ctx, oprot)
	oprot.WriteMessageEnd(ctx)
	oprot.Flush(ctx)
	return false, x14
}

type giftServiceProcessorSendGift struct {
	handler GiftService
}

func (p *giftServiceProcessorSendGift) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	var _write_err15 thrift.TException
	args := GiftServiceSendGiftArgs{}
	if err2 := args.Read(ctx, iprot); err2 != nil {
		iprot.ReadMessageEnd(ctx)
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err2.Error())
		oprot.WriteMessageBegin(ctx, "SendGift", thrift.EXCEPTION, seqId)
		x.Write(ctx, oprot)
		oprot.WriteMessageEnd(ctx)
		oprot.Flush(ctx)
		return false, thrift.WrapTException(err2)
	}
	iprot.ReadMessageEnd(ctx)

	tickerCancel := func() {}
	// Start a goroutine to do server side connectivity check.
	if thrift.ServerConnectivityCheckInterval > 0 {
		var cancel context.CancelCauseFunc
		ctx, cancel = context.WithCancelCause(ctx)
		defer cancel(nil)
		var tickerCtx context.Context
		tickerCtx, tickerCancel = context.WithCancel(context.Background())
		defer tickerCancel()
		go func(ctx context.Context, cancel context.CancelCauseFunc) {
			ticker := time.NewTicker(thrift.ServerConnectivityCheckInterval)
			defer ticker.Stop()
			for {
				select {
				case <-ctx.Done():
					return
				case <-ticker.C:
					if !iprot.Transport().IsOpen() {
						cancel(thrift.ErrAbandonRequest)
						return
					}
				}
			}
		}(tickerCtx, cancel)
	}

	result := GiftServiceSendGiftResult{}
	if retval, err2 := p.handler.SendGift(ctx, args.SenderId, args.ReceiverId, args.Price, args.GiftType, args.Quantity); err2 != nil {
		tickerCancel()
		err = thrift.WrapTException(err2)
		if errors.Is(err2, thrift.ErrAbandonRequest) {
			return false, &thrift.ProcessorError{
				WriteError:    thrift.WrapTException(err2),
				EndpointError: err,
			}
		}
		if errors.Is(err2, context.Canceled) {
			if err3 := context.Cause(ctx); errors.Is(err3, thrift.ErrAbandonRequest) {
				return false, &thrift.ProcessorError{
					WriteError:    thrift.WrapTException(err3),
					EndpointError: err,
				}
			}
		}
		_exc16 := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing SendGift: "+err2.Error())
		if err2 := oprot.WriteMessageBegin(ctx, "SendGift", thrift.EXCEPTION, seqId); err2 != nil {
			_write_err15 = thrift.WrapTException(err2)
		}
		if err2 := _exc16.Write(ctx, oprot); _write_err15 == nil && err2 != nil {
			_write_err15 = thrift.WrapTException(err2)
		}
		if err2 := oprot.WriteMessageEnd(ctx); _write_err15 == nil && err2 != nil {
			_write_err15 = thrift.WrapTException(err2)
		}
		if err2 := oprot.Flush(ctx); _write_err15 == nil && err2 != nil {
			_write_err15 = thrift.WrapTException(err2)
		}
		if _write_err15 != nil {
			return false, &thrift.ProcessorError{
				WriteError:    _write_err15,
				EndpointError: err,
			}
		}
		return true, err
	} else {
		result.Success = retval
	}
	tickerCancel()
	if err2 := oprot.WriteMessageBegin(ctx, "SendGift", thrift.REPLY, seqId); err2 != nil {
		_write_err15 = thrift.WrapTException(err2)
	}
	if err2 := result.Write(ctx, oprot); _write_err15 == nil && err2 != nil {
		_write_err15 = thrift.WrapTException(err2)
	}
	if err2 := oprot.WriteMessageEnd(ctx); _write_err15 == nil && err2 != nil {
		_write_err15 = thrift.WrapTException(err2)
	}
	if err2 := oprot.Flush(ctx); _write_err15 == nil && err2 != nil {
		_write_err15 = thrift.WrapTException(err2)
	}
	if _write_err15 != nil {
		return false, &thrift.ProcessorError{
			WriteError:    _write_err15,
			EndpointError: err,
		}
	}
	return true, err
}

type giftServiceProcessorGetTop10Senders struct {
	handler GiftService
}

func (p *giftServiceProcessorGetTop10Senders) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	var _write_err17 thrift.TException
	args := GiftServiceGetTop10SendersArgs{}
	if err2 := args.Read(ctx, iprot); err2 != nil {
		iprot.ReadMessageEnd(ctx)
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err2.Error())
		oprot.WriteMessageBegin(ctx, "GetTop10Senders", thrift.EXCEPTION, seqId)
		x.Write(ctx, oprot)
		oprot.WriteMessageEnd(ctx)
		oprot.Flush(ctx)
		return false, thrift.WrapTException(err2)
	}
	iprot.ReadMessageEnd(ctx)

	tickerCancel := func() {}
	// Start a goroutine to do server side connectivity check.
	if thrift.ServerConnectivityCheckInterval > 0 {
		var cancel context.CancelCauseFunc
		ctx, cancel = context.WithCancelCause(ctx)
		defer cancel(nil)
		var tickerCtx context.Context
		tickerCtx, tickerCancel = context.WithCancel(context.Background())
		defer tickerCancel()
		go func(ctx context.Context, cancel context.CancelCauseFunc) {
			ticker := time.NewTicker(thrift.ServerConnectivityCheckInterval)
			defer ticker.Stop()
			for {
				select {
				case <-ctx.Done():
					return
				case <-ticker.C:
					if !iprot.Transport().IsOpen() {
						cancel(thrift.ErrAbandonRequest)
						return
					}
				}
			}
		}(tickerCtx, cancel)
	}

	result := GiftServiceGetTop10SendersResult{}
	if retval, err2 := p.handler.GetTop10Senders(ctx); err2 != nil {
		tickerCancel()
		err = thrift.WrapTException(err2)
		if errors.Is(err2, thrift.ErrAbandonRequest) {
			return false, &thrift.ProcessorError{
				WriteError:    thrift.WrapTException(err2),
				EndpointError: err,
			}
		}
		if errors.Is(err2, context.Canceled) {
			if err3 := context.Cause(ctx); errors.Is(err3, thrift.ErrAbandonRequest) {
				return false, &thrift.ProcessorError{
					WriteError:    thrift.WrapTException(err3),
					EndpointError: err,
				}
			}
		}
		_exc18 := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing GetTop10Senders: "+err2.Error())
		if err2 := oprot.WriteMessageBegin(ctx, "GetTop10Senders", thrift.EXCEPTION, seqId); err2 != nil {
			_write_err17 = thrift.WrapTException(err2)
		}
		if err2 := _exc18.Write(ctx, oprot); _write_err17 == nil && err2 != nil {
			_write_err17 = thrift.WrapTException(err2)
		}
		if err2 := oprot.WriteMessageEnd(ctx); _write_err17 == nil && err2 != nil {
			_write_err17 = thrift.WrapTException(err2)
		}
		if err2 := oprot.Flush(ctx); _write_err17 == nil && err2 != nil {
			_write_err17 = thrift.WrapTException(err2)
		}
		if _write_err17 != nil {
			return false, &thrift.ProcessorError{
				WriteError:    _write_err17,
				EndpointError: err,
			}
		}
		return true, err
	} else {
		result.Success = retval
	}
	tickerCancel()
	if err2 := oprot.WriteMessageBegin(ctx, "GetTop10Senders", thrift.REPLY, seqId); err2 != nil {
		_write_err17 = thrift.WrapTException(err2)
	}
	if err2 := result.Write(ctx, oprot); _write_err17 == nil && err2 != nil {
		_write_err17 = thrift.WrapTException(err2)
	}
	if err2 := oprot.WriteMessageEnd(ctx); _write_err17 == nil && err2 != nil {
		_write_err17 = thrift.WrapTException(err2)
	}
	if err2 := oprot.Flush(ctx); _write_err17 == nil && err2 != nil {
		_write_err17 = thrift.WrapTException(err2)
	}
	if _write_err17 != nil {
		return false, &thrift.ProcessorError{
			WriteError:    _write_err17,
			EndpointError: err,
		}
	}
	return true, err
}

type giftServiceProcessorGetSendersInLastWeek struct {
	handler GiftService
}

func (p *giftServiceProcessorGetSendersInLastWeek) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	var _write_err19 thrift.TException
	args := GiftServiceGetSendersInLastWeekArgs{}
	if err2 := args.Read(ctx, iprot); err2 != nil {
		iprot.ReadMessageEnd(ctx)
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err2.Error())
		oprot.WriteMessageBegin(ctx, "GetSendersInLastWeek", thrift.EXCEPTION, seqId)
		x.Write(ctx, oprot)
		oprot.WriteMessageEnd(ctx)
		oprot.Flush(ctx)
		return false, thrift.WrapTException(err2)
	}
	iprot.ReadMessageEnd(ctx)

	tickerCancel := func() {}
	// Start a goroutine to do server side connectivity check.
	if thrift.ServerConnectivityCheckInterval > 0 {
		var cancel context.CancelCauseFunc
		ctx, cancel = context.WithCancelCause(ctx)
		defer cancel(nil)
		var tickerCtx context.Context
		tickerCtx, tickerCancel = context.WithCancel(context.Background())
		defer tickerCancel()
		go func(ctx context.Context, cancel context.CancelCauseFunc) {
			ticker := time.NewTicker(thrift.ServerConnectivityCheckInterval)
			defer ticker.Stop()
			for {
				select {
				case <-ctx.Done():
					return
				case <-ticker.C:
					if !iprot.Transport().IsOpen() {
						cancel(thrift.ErrAbandonRequest)
						return
					}
				}
			}
		}(tickerCtx, cancel)
	}

	result := GiftServiceGetSendersInLastWeekResult{}
	if retval, err2 := p.handler.GetSendersInLastWeek(ctx); err2 != nil {
		tickerCancel()
		err = thrift.WrapTException(err2)
		if errors.Is(err2, thrift.ErrAbandonRequest) {
			return false, &thrift.ProcessorError{
				WriteError:    thrift.WrapTException(err2),
				EndpointError: err,
			}
		}
		if errors.Is(err2, context.Canceled) {
			if err3 := context.Cause(ctx); errors.Is(err3, thrift.ErrAbandonRequest) {
				return false, &thrift.ProcessorError{
					WriteError:    thrift.WrapTException(err3),
					EndpointError: err,
				}
			}
		}
		_exc20 := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing GetSendersInLastWeek: "+err2.Error())
		if err2 := oprot.WriteMessageBegin(ctx, "GetSendersInLastWeek", thrift.EXCEPTION, seqId); err2 != nil {
			_write_err19 = thrift.WrapTException(err2)
		}
		if err2 := _exc20.Write(ctx, oprot); _write_err19 == nil && err2 != nil {
			_write_err19 = thrift.WrapTException(err2)
		}
		if err2 := oprot.WriteMessageEnd(ctx); _write_err19 == nil && err2 != nil {
			_write_err19 = thrift.WrapTException(err2)
		}
		if err2 := oprot.Flush(ctx); _write_err19 == nil && err2 != nil {
			_write_err19 = thrift.WrapTException(err2)
		}
		if _write_err19 != nil {
			return false, &thrift.ProcessorError{
				WriteError:    _write_err19,
				EndpointError: err,
			}
		}
		return true, err
	} else {
		result.Success = retval
	}
	tickerCancel()
	if err2 := oprot.WriteMessageBegin(ctx, "GetSendersInLastWeek", thrift.REPLY, seqId); err2 != nil {
		_write_err19 = thrift.WrapTException(err2)
	}
	if err2 := result.Write(ctx, oprot); _write_err19 == nil && err2 != nil {
		_write_err19 = thrift.WrapTException(err2)
	}
	if err2 := oprot.WriteMessageEnd(ctx); _write_err19 == nil && err2 != nil {
		_write_err19 = thrift.WrapTException(err2)
	}
	if err2 := oprot.Flush(ctx); _write_err19 == nil && err2 != nil {
		_write_err19 = thrift.WrapTException(err2)
	}
	if _write_err19 != nil {
		return false, &thrift.ProcessorError{
			WriteError:    _write_err19,
			EndpointError: err,
		}
	}
	return true, err
}

type giftServiceProcessorGetGiftsBySender struct {
	handler GiftService
}

func (p *giftServiceProcessorGetGiftsBySender) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	var _write_err21 thrift.TException
	args := GiftServiceGetGiftsBySenderArgs{}
	if err2 := args.Read(ctx, iprot); err2 != nil {
		iprot.ReadMessageEnd(ctx)
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err2.Error())
		oprot.WriteMessageBegin(ctx, "GetGiftsBySender", thrift.EXCEPTION, seqId)
		x.Write(ctx, oprot)
		oprot.WriteMessageEnd(ctx)
		oprot.Flush(ctx)
		return false, thrift.WrapTException(err2)
	}
	iprot.ReadMessageEnd(ctx)

	tickerCancel := func() {}
	// Start a goroutine to do server side connectivity check.
	if thrift.ServerConnectivityCheckInterval > 0 {
		var cancel context.CancelCauseFunc
		ctx, cancel = context.WithCancelCause(ctx)
		defer cancel(nil)
		var tickerCtx context.Context
		tickerCtx, tickerCancel = context.WithCancel(context.Background())
		defer tickerCancel()
		go func(ctx context.Context, cancel context.CancelCauseFunc) {
			ticker := time.NewTicker(thrift.ServerConnectivityCheckInterval)
			defer ticker.Stop()
			for {
				select {
				case <-ctx.Done():
					return
				case <-ticker.C:
					if !iprot.Transport().IsOpen() {
						cancel(thrift.ErrAbandonRequest)
						return
					}
				}
			}
		}(tickerCtx, cancel)
	}

	result := GiftServiceGetGiftsBySenderResult{}
	if retval, err2 := p.handler.GetGiftsBySender(ctx, args.SenderId); err2 != nil {
		tickerCancel()
		err = thrift.WrapTException(err2)
		if errors.Is(err2, thrift.ErrAbandonRequest) {
			return false, &thrift.ProcessorError{
				WriteError:    thrift.WrapTException(err2),
				EndpointError: err,
			}
		}
		if errors.Is(err2, context.Canceled) {
			if err3 := context.Cause(ctx); errors.Is(err3, thrift.ErrAbandonRequest) {
				return false, &thrift.ProcessorError{
					WriteError:    thrift.WrapTException(err3),
					EndpointError: err,
				}
			}
		}
		_exc22 := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing GetGiftsBySender: "+err2.Error())
		if err2 := oprot.WriteMessageBegin(ctx, "GetGiftsBySender", thrift.EXCEPTION, seqId); err2 != nil {
			_write_err21 = thrift.WrapTException(err2)
		}
		if err2 := _exc22.Write(ctx, oprot); _write_err21 == nil && err2 != nil {
			_write_err21 = thrift.WrapTException(err2)
		}
		if err2 := oprot.WriteMessageEnd(ctx); _write_err21 == nil && err2 != nil {
			_write_err21 = thrift.WrapTException(err2)
		}
		if err2 := oprot.Flush(ctx); _write_err21 == nil && err2 != nil {
			_write_err21 = thrift.WrapTException(err2)
		}
		if _write_err21 != nil {
			return false, &thrift.ProcessorError{
				WriteError:    _write_err21,
				EndpointError: err,
			}
		}
		return true, err
	} else {
		result.Success = retval
	}
	tickerCancel()
	if err2 := oprot.WriteMessageBegin(ctx, "GetGiftsBySender", thrift.REPLY, seqId); err2 != nil {
		_write_err21 = thrift.WrapTException(err2)
	}
	if err2 := result.Write(ctx, oprot); _write_err21 == nil && err2 != nil {
		_write_err21 = thrift.WrapTException(err2)
	}
	if err2 := oprot.WriteMessageEnd(ctx); _write_err21 == nil && err2 != nil {
		_write_err21 = thrift.WrapTException(err2)
	}
	if err2 := oprot.Flush(ctx); _write_err21 == nil && err2 != nil {
		_write_err21 = thrift.WrapTException(err2)
	}
	if _write_err21 != nil {
		return false, &thrift.ProcessorError{
			WriteError:    _write_err21,
			EndpointError: err,
		}
	}
	return true, err
}

// HELPER FUNCTIONS AND STRUCTURES

// Attributes:
//   - SenderId
//   - ReceiverId
//   - Price
//   - GiftType
//   - Quantity
type GiftServiceSendGiftArgs struct {
	SenderId   int64    `thrift:"senderId,1" db:"senderId" json:"senderId"`
	ReceiverId int64    `thrift:"receiverId,2" db:"receiverId" json:"receiverId"`
	Price      int32    `thrift:"price,3" db:"price" json:"price"`
	GiftType   GiftType `thrift:"giftType,4" db:"giftType" json:"giftType"`
	Quantity   int32    `thrift:"quantity,5" db:"quantity" json:"quantity"`
}

func NewGiftServiceSendGiftArgs() *GiftServiceSendGiftArgs {
	return &GiftServiceSendGiftArgs{}
}

func (p *GiftServiceSendGiftArgs) GetSenderId() int64 {
	return p.SenderId
}

func (p *GiftServiceSendGiftArgs) GetReceiverId() int64 {
	return p.ReceiverId
}

func (p *GiftServiceSendGiftArgs) GetPrice() int32 {
	return p.Price
}

func (p *GiftServiceSendGiftArgs) GetGiftType() GiftType {
	return p.GiftType
}

func (p *GiftServiceSendGiftArgs) GetQuantity() int32 {
	return p.Quantity
}

func (p *GiftServiceSendGiftArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I64 {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.I64 {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 3:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField3(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 4:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField4(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 5:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField5(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *GiftServiceSendGiftArgs) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.SenderId = v
	}
	return nil
}

func (p *GiftServiceSendGiftArgs) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(ctx); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.ReceiverId = v
	}
	return nil
}

func (p *GiftServiceSendGiftArgs) ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 3: ", err)
	} else {
		p.Price = v
	}
	return nil
}

func (p *GiftServiceSendGiftArgs) ReadField4(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 4: ", err)
	} else {
		temp := GiftType(v)
		p.GiftType = temp
	}
	return nil
}

func (p *GiftServiceSendGiftArgs) ReadField5(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 5: ", err)
	} else {
		p.Quantity = v
	}
	return nil
}

func (p *GiftServiceSendGiftArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "SendGift_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField2(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField3(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField4(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField5(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *GiftServiceSendGiftArgs) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "senderId", thrift.I64, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:senderId: ", p), err)
	}
	if err := oprot.WriteI64(ctx, int64(p.SenderId)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.senderId (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:senderId: ", p), err)
	}
	return err
}

func (p *GiftServiceSendGiftArgs) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "receiverId", thrift.I64, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:receiverId: ", p), err)
	}
	if err := oprot.WriteI64(ctx, int64(p.ReceiverId)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.receiverId (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:receiverId: ", p), err)
	}
	return err
}

func (p *GiftServiceSendGiftArgs) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "price", thrift.I32, 3); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:price: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.Price)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.price (3) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 3:price: ", p), err)
	}
	return err
}

func (p *GiftServiceSendGiftArgs) writeField4(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "giftType", thrift.I32, 4); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:giftType: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.GiftType)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.giftType (4) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 4:giftType: ", p), err)
	}
	return err
}

func (p *GiftServiceSendGiftArgs) writeField5(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "quantity", thrift.I32, 5); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 5:quantity: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.Quantity)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.quantity (5) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 5:quantity: ", p), err)
	}
	return err
}

func (p *GiftServiceSendGiftArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GiftServiceSendGiftArgs(%+v)", *p)
}

func (p *GiftServiceSendGiftArgs) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*gift_service.GiftServiceSendGiftArgs",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*GiftServiceSendGiftArgs)(nil)

// Attributes:
//   - Success
type GiftServiceSendGiftResult struct {
	Success *Gift `thrift:"success,0" db:"success" json:"success,omitempty"`
}

func NewGiftServiceSendGiftResult() *GiftServiceSendGiftResult {
	return &GiftServiceSendGiftResult{}
}

var GiftServiceSendGiftResult_Success_DEFAULT *Gift

func (p *GiftServiceSendGiftResult) GetSuccess() *Gift {
	if !p.IsSetSuccess() {
		return GiftServiceSendGiftResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GiftServiceSendGiftResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GiftServiceSendGiftResult) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField0(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *GiftServiceSendGiftResult) ReadField0(ctx context.Context, iprot thrift.TProtocol) error {
	p.Success = &Gift{}
	if err := p.Success.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Success), err)
	}
	return nil
}

func (p *GiftServiceSendGiftResult) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "SendGift_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField0(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *GiftServiceSendGiftResult) writeField0(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin(ctx, "success", thrift.STRUCT, 0); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err)
		}
		if err := p.Success.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Success), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err)
		}
	}
	return err
}

func (p *GiftServiceSendGiftResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GiftServiceSendGiftResult(%+v)", *p)
}

func (p *GiftServiceSendGiftResult) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*gift_service.GiftServiceSendGiftResult",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*GiftServiceSendGiftResult)(nil)

type GiftServiceGetTop10SendersArgs struct {
}

func NewGiftServiceGetTop10SendersArgs() *GiftServiceGetTop10SendersArgs {
	return &GiftServiceGetTop10SendersArgs{}
}

func (p *GiftServiceGetTop10SendersArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		if err := iprot.Skip(ctx, fieldTypeId); err != nil {
			return err
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *GiftServiceGetTop10SendersArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "GetTop10Senders_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *GiftServiceGetTop10SendersArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GiftServiceGetTop10SendersArgs(%+v)", *p)
}

func (p *GiftServiceGetTop10SendersArgs) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*gift_service.GiftServiceGetTop10SendersArgs",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*GiftServiceGetTop10SendersArgs)(nil)

// Attributes:
//   - Success
type GiftServiceGetTop10SendersResult struct {
	Success []int64 `thrift:"success,0" db:"success" json:"success,omitempty"`
}

func NewGiftServiceGetTop10SendersResult() *GiftServiceGetTop10SendersResult {
	return &GiftServiceGetTop10SendersResult{}
}

var GiftServiceGetTop10SendersResult_Success_DEFAULT []int64

func (p *GiftServiceGetTop10SendersResult) GetSuccess() []int64 {
	return p.Success
}

func (p *GiftServiceGetTop10SendersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GiftServiceGetTop10SendersResult) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if fieldTypeId == thrift.LIST {
				if err := p.ReadField0(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *GiftServiceGetTop10SendersResult) ReadField0(ctx context.Context, iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin(ctx)
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]int64, 0, size)
	p.Success = tSlice
	for i := 0; i < size; i++ {
		var _elem23 int64
		if v, err := iprot.ReadI64(ctx); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_elem23 = v
		}
		p.Success = append(p.Success, _elem23)
	}
	if err := iprot.ReadListEnd(ctx); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *GiftServiceGetTop10SendersResult) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "GetTop10Senders_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField0(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *GiftServiceGetTop10SendersResult) writeField0(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin(ctx, "success", thrift.LIST, 0); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err)
		}
		if err := oprot.WriteListBegin(ctx, thrift.I64, len(p.Success)); err != nil {
			return thrift.PrependError("error writing list begin: ", err)
		}
		for _, v := range p.Success {
			if err := oprot.WriteI64(ctx, int64(v)); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
			}
		}
		if err := oprot.WriteListEnd(ctx); err != nil {
			return thrift.PrependError("error writing list end: ", err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err)
		}
	}
	return err
}

func (p *GiftServiceGetTop10SendersResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GiftServiceGetTop10SendersResult(%+v)", *p)
}

func (p *GiftServiceGetTop10SendersResult) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*gift_service.GiftServiceGetTop10SendersResult",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*GiftServiceGetTop10SendersResult)(nil)

type GiftServiceGetSendersInLastWeekArgs struct {
}

func NewGiftServiceGetSendersInLastWeekArgs() *GiftServiceGetSendersInLastWeekArgs {
	return &GiftServiceGetSendersInLastWeekArgs{}
}

func (p *GiftServiceGetSendersInLastWeekArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		if err := iprot.Skip(ctx, fieldTypeId); err != nil {
			return err
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *GiftServiceGetSendersInLastWeekArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "GetSendersInLastWeek_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *GiftServiceGetSendersInLastWeekArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GiftServiceGetSendersInLastWeekArgs(%+v)", *p)
}

func (p *GiftServiceGetSendersInLastWeekArgs) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*gift_service.GiftServiceGetSendersInLastWeekArgs",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*GiftServiceGetSendersInLastWeekArgs)(nil)

// Attributes:
//   - Success
type GiftServiceGetSendersInLastWeekResult struct {
	Success []int64 `thrift:"success,0" db:"success" json:"success,omitempty"`
}

func NewGiftServiceGetSendersInLastWeekResult() *GiftServiceGetSendersInLastWeekResult {
	return &GiftServiceGetSendersInLastWeekResult{}
}

var GiftServiceGetSendersInLastWeekResult_Success_DEFAULT []int64

func (p *GiftServiceGetSendersInLastWeekResult) GetSuccess() []int64 {
	return p.Success
}

func (p *GiftServiceGetSendersInLastWeekResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GiftServiceGetSendersInLastWeekResult) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if fieldTypeId == thrift.LIST {
				if err := p.ReadField0(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *GiftServiceGetSendersInLastWeekResult) ReadField0(ctx context.Context, iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin(ctx)
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]int64, 0, size)
	p.Success = tSlice
	for i := 0; i < size; i++ {
		var _elem24 int64
		if v, err := iprot.ReadI64(ctx); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_elem24 = v
		}
		p.Success = append(p.Success, _elem24)
	}
	if err := iprot.ReadListEnd(ctx); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *GiftServiceGetSendersInLastWeekResult) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "GetSendersInLastWeek_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField0(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *GiftServiceGetSendersInLastWeekResult) writeField0(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin(ctx, "success", thrift.LIST, 0); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err)
		}
		if err := oprot.WriteListBegin(ctx, thrift.I64, len(p.Success)); err != nil {
			return thrift.PrependError("error writing list begin: ", err)
		}
		for _, v := range p.Success {
			if err := oprot.WriteI64(ctx, int64(v)); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
			}
		}
		if err := oprot.WriteListEnd(ctx); err != nil {
			return thrift.PrependError("error writing list end: ", err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err)
		}
	}
	return err
}

func (p *GiftServiceGetSendersInLastWeekResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GiftServiceGetSendersInLastWeekResult(%+v)", *p)
}

func (p *GiftServiceGetSendersInLastWeekResult) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*gift_service.GiftServiceGetSendersInLastWeekResult",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*GiftServiceGetSendersInLastWeekResult)(nil)

// Attributes:
//   - SenderId
type GiftServiceGetGiftsBySenderArgs struct {
	SenderId int64 `thrift:"senderId,1" db:"senderId" json:"senderId"`
}

func NewGiftServiceGetGiftsBySenderArgs() *GiftServiceGetGiftsBySenderArgs {
	return &GiftServiceGetGiftsBySenderArgs{}
}

func (p *GiftServiceGetGiftsBySenderArgs) GetSenderId() int64 {
	return p.SenderId
}

func (p *GiftServiceGetGiftsBySenderArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I64 {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *GiftServiceGetGiftsBySenderArgs) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.SenderId = v
	}
	return nil
}

func (p *GiftServiceGetGiftsBySenderArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "GetGiftsBySender_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *GiftServiceGetGiftsBySenderArgs) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "senderId", thrift.I64, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:senderId: ", p), err)
	}
	if err := oprot.WriteI64(ctx, int64(p.SenderId)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.senderId (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:senderId: ", p), err)
	}
	return err
}

func (p *GiftServiceGetGiftsBySenderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GiftServiceGetGiftsBySenderArgs(%+v)", *p)
}

func (p *GiftServiceGetGiftsBySenderArgs) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*gift_service.GiftServiceGetGiftsBySenderArgs",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*GiftServiceGetGiftsBySenderArgs)(nil)

// Attributes:
//   - Success
type GiftServiceGetGiftsBySenderResult struct {
	Success []*Gift `thrift:"success,0" db:"success" json:"success,omitempty"`
}

func NewGiftServiceGetGiftsBySenderResult() *GiftServiceGetGiftsBySenderResult {
	return &GiftServiceGetGiftsBySenderResult{}
}

var GiftServiceGetGiftsBySenderResult_Success_DEFAULT []*Gift

func (p *GiftServiceGetGiftsBySenderResult) GetSuccess() []*Gift {
	return p.Success
}

func (p *GiftServiceGetGiftsBySenderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GiftServiceGetGiftsBySenderResult) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if fieldTypeId == thrift.LIST {
				if err := p.ReadField0(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *GiftServiceGetGiftsBySenderResult) ReadField0(ctx context.Context, iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin(ctx)
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]*Gift, 0, size)
	p.Success = tSlice
	for i := 0; i < size; i++ {
		_elem25 := &Gift{}
		if err := _elem25.Read(ctx, iprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _elem25), err)
		}
		p.Success = append(p.Success, _elem25)
	}
	if err := iprot.ReadListEnd(ctx); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *GiftServiceGetGiftsBySenderResult) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "GetGiftsBySender_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField0(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *GiftServiceGetGiftsBySenderResult) writeField0(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin(ctx, "success", thrift.LIST, 0); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err)
		}
		if err := oprot.WriteListBegin(ctx, thrift.STRUCT, len(p.Success)); err != nil {
			return thrift.PrependError("error writing list begin: ", err)
		}
		for _, v := range p.Success {
			if err := v.Write(ctx, oprot); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
			}
		}
		if err := oprot.WriteListEnd(ctx); err != nil {
			return thrift.PrependError("error writing list end: ", err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err)
		}
	}
	return err
}

func (p *GiftServiceGetGiftsBySenderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GiftServiceGetGiftsBySenderResult(%+v)", *p)
}

func (p *GiftServiceGetGiftsBySenderResult) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*gift_service.GiftServiceGetGiftsBySenderResult",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*GiftServiceGetGiftsBySenderResult)(nil)
