// Code generated by Thrift Compiler (0.22.0). DO NOT EDIT.

package user_service

import (
	"bytes"
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"log/slog"
	"time"
	thrift "github.com/apache/thrift/lib/go/thrift"
	"strings"
	"regexp"
)

// (needed to ensure safety because of naive import list construction.)
var _ = bytes.Equal
var _ = context.Background
var _ = errors.New
var _ = fmt.Printf
var _ = iter.Pull[int]
var _ = slog.Log
var _ = time.Now
var _ = thrift.ZERO
// (needed by validator.)
var _ = strings.Contains
var _ = regexp.MatchString

type UserRole int64

const (
	UserRole_ADMIN UserRole = 1
	UserRole_USER UserRole = 2
	UserRole_GUEST UserRole = 3
)

var knownUserRoleValues = []UserRole{
	UserRole_ADMIN,
	UserRole_USER,
	UserRole_GUEST,
}

func UserRoleValues() iter.Seq[UserRole] {
	return func(yield func(UserRole) bool) {
		for _, v := range knownUserRoleValues {
			if !yield(v) {
				return
			}
		}
	}
}

func (p UserRole) String() string {
	switch p {
	case UserRole_ADMIN: return "ADMIN"
	case UserRole_USER: return "USER"
	case UserRole_GUEST: return "GUEST"
	}
	return "<UNSET>"
}

func UserRoleFromString(s string) (UserRole, error) {
	switch s {
	case "ADMIN": return UserRole_ADMIN, nil
	case "USER": return UserRole_USER, nil
	case "GUEST": return UserRole_GUEST, nil
	}
	return UserRole(0), fmt.Errorf("not a valid UserRole string")
}


func UserRolePtr(v UserRole) *UserRole { return &v }

func (p UserRole) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *UserRole) UnmarshalText(text []byte) error {
	q, err := UserRoleFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *UserRole) Scan(value interface{}) error {
	v, ok := value.(int64)
	if !ok {
		return errors.New("Scan value is not int64")
	}
	*p = UserRole(v)
	return nil
}

func (p *UserRole) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

// Attributes:
//  - Street
//  - City
//  - State
//  - ZipCode
// 
type Address struct {
	Street string `thrift:"street,1" db:"street" json:"street"`
	City string `thrift:"city,2" db:"city" json:"city"`
	State string `thrift:"state,3" db:"state" json:"state"`
	ZipCode string `thrift:"zipCode,4" db:"zipCode" json:"zipCode"`
}

func NewAddress() *Address {
	return &Address{}
}



func (p *Address) GetStreet() string {
	return p.Street
}



func (p *Address) GetCity() string {
	return p.City
}



func (p *Address) GetState() string {
	return p.State
}



func (p *Address) GetZipCode() string {
	return p.ZipCode
}

func (p *Address) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}


	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 3:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField3(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 4:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField4(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *Address) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Street = v
	}
	return nil
}

func (p *Address) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.City = v
	}
	return nil
}

func (p *Address) ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 3: ", err)
	} else {
		p.State = v
	}
	return nil
}

func (p *Address) ReadField4(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 4: ", err)
	} else {
		p.ZipCode = v
	}
	return nil
}

func (p *Address) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "Address"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil { return err }
		if err := p.writeField2(ctx, oprot); err != nil { return err }
		if err := p.writeField3(ctx, oprot); err != nil { return err }
		if err := p.writeField4(ctx, oprot); err != nil { return err }
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *Address) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "street", thrift.STRING, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:street: ", p), err)
	}
	if err := oprot.WriteString(ctx, string(p.Street)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.street (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:street: ", p), err)
	}
	return err
}

func (p *Address) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "city", thrift.STRING, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:city: ", p), err)
	}
	if err := oprot.WriteString(ctx, string(p.City)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.city (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:city: ", p), err)
	}
	return err
}

func (p *Address) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "state", thrift.STRING, 3); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:state: ", p), err)
	}
	if err := oprot.WriteString(ctx, string(p.State)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.state (3) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 3:state: ", p), err)
	}
	return err
}

func (p *Address) writeField4(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "zipCode", thrift.STRING, 4); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:zipCode: ", p), err)
	}
	if err := oprot.WriteString(ctx, string(p.ZipCode)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.zipCode (4) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 4:zipCode: ", p), err)
	}
	return err
}

func (p *Address) Equals(other *Address) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if p.Street != other.Street { return false }
	if p.City != other.City { return false }
	if p.State != other.State { return false }
	if p.ZipCode != other.ZipCode { return false }
	return true
}

func (p *Address) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Address(%+v)", *p)
}

func (p *Address) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type: "*user_service.Address",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*Address)(nil)

func (p *Address) Validate() error {
	return nil
}

// Attributes:
//  - Phone
//  - Website
//  - Address
//  - Metadata
// 
type UserDetails struct {
	Phone *string `thrift:"phone,1" db:"phone" json:"phone,omitempty"`
	Website *string `thrift:"website,2" db:"website" json:"website,omitempty"`
	Address *Address `thrift:"address,3" db:"address" json:"address,omitempty"`
	Metadata map[string]string `thrift:"metadata,4" db:"metadata" json:"metadata,omitempty"`
}

func NewUserDetails() *UserDetails {
	return &UserDetails{}
}

var UserDetails_Phone_DEFAULT string

func (p *UserDetails) GetPhone() string {
	if !p.IsSetPhone() {
		return UserDetails_Phone_DEFAULT
	}
	return *p.Phone
}

var UserDetails_Website_DEFAULT string

func (p *UserDetails) GetWebsite() string {
	if !p.IsSetWebsite() {
		return UserDetails_Website_DEFAULT
	}
	return *p.Website
}

var UserDetails_Address_DEFAULT *Address

func (p *UserDetails) GetAddress() *Address {
	if !p.IsSetAddress() {
		return UserDetails_Address_DEFAULT
	}
	return p.Address
}

var UserDetails_Metadata_DEFAULT map[string]string


func (p *UserDetails) GetMetadata() map[string]string {
	return p.Metadata
}

func (p *UserDetails) IsSetPhone() bool {
	return p.Phone != nil
}

func (p *UserDetails) IsSetWebsite() bool {
	return p.Website != nil
}

func (p *UserDetails) IsSetAddress() bool {
	return p.Address != nil
}

func (p *UserDetails) IsSetMetadata() bool {
	return p.Metadata != nil
}

func (p *UserDetails) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}


	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 3:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField3(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 4:
			if fieldTypeId == thrift.MAP {
				if err := p.ReadField4(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *UserDetails) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Phone = &v
	}
	return nil
}

func (p *UserDetails) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.Website = &v
	}
	return nil
}

func (p *UserDetails) ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
	p.Address = &Address{}
	if err := p.Address.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Address), err)
	}
	return nil
}

func (p *UserDetails) ReadField4(ctx context.Context, iprot thrift.TProtocol) error {
	_, _, size, err := iprot.ReadMapBegin(ctx)
	if err != nil {
		return thrift.PrependError("error reading map begin: ", err)
	}
	tMap := make(map[string]string, size)
	p.Metadata = tMap
	for i := 0; i < size; i++ {
		var _key0 string
		if v, err := iprot.ReadString(ctx); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_key0 = v
		}
		var _val1 string
		if v, err := iprot.ReadString(ctx); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_val1 = v
		}
		p.Metadata[_key0] = _val1
	}
	if err := iprot.ReadMapEnd(ctx); err != nil {
		return thrift.PrependError("error reading map end: ", err)
	}
	return nil
}

func (p *UserDetails) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "UserDetails"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil { return err }
		if err := p.writeField2(ctx, oprot); err != nil { return err }
		if err := p.writeField3(ctx, oprot); err != nil { return err }
		if err := p.writeField4(ctx, oprot); err != nil { return err }
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *UserDetails) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetPhone() {
		if err := oprot.WriteFieldBegin(ctx, "phone", thrift.STRING, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:phone: ", p), err)
		}
		if err := oprot.WriteString(ctx, string(*p.Phone)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.phone (1) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:phone: ", p), err)
		}
	}
	return err
}

func (p *UserDetails) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetWebsite() {
		if err := oprot.WriteFieldBegin(ctx, "website", thrift.STRING, 2); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:website: ", p), err)
		}
		if err := oprot.WriteString(ctx, string(*p.Website)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.website (2) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 2:website: ", p), err)
		}
	}
	return err
}

func (p *UserDetails) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetAddress() {
		if err := oprot.WriteFieldBegin(ctx, "address", thrift.STRUCT, 3); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:address: ", p), err)
		}
		if err := p.Address.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Address), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 3:address: ", p), err)
		}
	}
	return err
}

func (p *UserDetails) writeField4(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetMetadata() {
		if err := oprot.WriteFieldBegin(ctx, "metadata", thrift.MAP, 4); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:metadata: ", p), err)
		}
		if err := oprot.WriteMapBegin(ctx, thrift.STRING, thrift.STRING, len(p.Metadata)); err != nil {
			return thrift.PrependError("error writing map begin: ", err)
		}
		for k, v := range p.Metadata {
			if err := oprot.WriteString(ctx, string(k)); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
			}
			if err := oprot.WriteString(ctx, string(v)); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
			}
		}
		if err := oprot.WriteMapEnd(ctx); err != nil {
			return thrift.PrependError("error writing map end: ", err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 4:metadata: ", p), err)
		}
	}
	return err
}

func (p *UserDetails) Equals(other *UserDetails) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if p.Phone != other.Phone {
		if p.Phone == nil || other.Phone == nil {
			return false
		}
		if (*p.Phone) != (*other.Phone) { return false }
	}
	if p.Website != other.Website {
		if p.Website == nil || other.Website == nil {
			return false
		}
		if (*p.Website) != (*other.Website) { return false }
	}
	if !p.Address.Equals(other.Address) { return false }
	if len(p.Metadata) != len(other.Metadata) { return false }
	for k, _tgt := range p.Metadata {
		_src2 := other.Metadata[k]
		if _tgt != _src2 { return false }
	}
	return true
}

func (p *UserDetails) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserDetails(%+v)", *p)
}

func (p *UserDetails) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type: "*user_service.UserDetails",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*UserDetails)(nil)

func (p *UserDetails) Validate() error {
	return nil
}

// Attributes:
//  - ID
//  - Name
//  - Email
//  - Age
//  - Role
//  - Details
//  - Tags
//  - Attributes
//  - IsActive
//  - Balance
//  - CreatedAt
//  - Avatar
// 
type User struct {
	ID int64 `thrift:"id,1" db:"id" json:"id"`
	Name string `thrift:"name,2" db:"name" json:"name"`
	Email string `thrift:"email,3" db:"email" json:"email"`
	Age int32 `thrift:"age,4" db:"age" json:"age"`
	Role UserRole `thrift:"role,5" db:"role" json:"role"`
	Details *UserDetails `thrift:"details,6" db:"details" json:"details,omitempty"`
	Tags []string `thrift:"tags,7" db:"tags" json:"tags"`
	Attributes map[string]string `thrift:"attributes,8" db:"attributes" json:"attributes"`
	IsActive *bool `thrift:"isActive,9" db:"isActive" json:"isActive,omitempty"`
	Balance *float64 `thrift:"balance,10" db:"balance" json:"balance,omitempty"`
	CreatedAt *int64 `thrift:"createdAt,11" db:"createdAt" json:"createdAt,omitempty"`
	Avatar []byte `thrift:"avatar,12" db:"avatar" json:"avatar"`
}

func NewUser() *User {
	return &User{
		Role: 2,
		Tags: []string{
		},
		Attributes: map[string]string{
		},
	}
}



func (p *User) GetID() int64 {
	return p.ID
}



func (p *User) GetName() string {
	return p.Name
}



func (p *User) GetEmail() string {
	return p.Email
}



func (p *User) GetAge() int32 {
	return p.Age
}



func (p *User) GetRole() UserRole {
	return p.Role
}

var User_Details_DEFAULT *UserDetails

func (p *User) GetDetails() *UserDetails {
	if !p.IsSetDetails() {
		return User_Details_DEFAULT
	}
	return p.Details
}



func (p *User) GetTags() []string {
	return p.Tags
}



func (p *User) GetAttributes() map[string]string {
	return p.Attributes
}

var User_IsActive_DEFAULT bool

func (p *User) GetIsActive() bool {
	if !p.IsSetIsActive() {
		return User_IsActive_DEFAULT
	}
	return *p.IsActive
}

var User_Balance_DEFAULT float64

func (p *User) GetBalance() float64 {
	if !p.IsSetBalance() {
		return User_Balance_DEFAULT
	}
	return *p.Balance
}

var User_CreatedAt_DEFAULT int64

func (p *User) GetCreatedAt() int64 {
	if !p.IsSetCreatedAt() {
		return User_CreatedAt_DEFAULT
	}
	return *p.CreatedAt
}



func (p *User) GetAvatar() []byte {
	return p.Avatar
}

func (p *User) IsSetDetails() bool {
	return p.Details != nil
}

func (p *User) IsSetIsActive() bool {
	return p.IsActive != nil
}

func (p *User) IsSetBalance() bool {
	return p.Balance != nil
}

func (p *User) IsSetCreatedAt() bool {
	return p.CreatedAt != nil
}

func (p *User) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}


	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I64 {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 3:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField3(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 4:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField4(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 5:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField5(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 6:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField6(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 7:
			if fieldTypeId == thrift.LIST {
				if err := p.ReadField7(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 8:
			if fieldTypeId == thrift.MAP {
				if err := p.ReadField8(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 9:
			if fieldTypeId == thrift.BOOL {
				if err := p.ReadField9(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 10:
			if fieldTypeId == thrift.DOUBLE {
				if err := p.ReadField10(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 11:
			if fieldTypeId == thrift.I64 {
				if err := p.ReadField11(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 12:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField12(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *User) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.ID = v
	}
	return nil
}

func (p *User) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.Name = v
	}
	return nil
}

func (p *User) ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 3: ", err)
	} else {
		p.Email = v
	}
	return nil
}

func (p *User) ReadField4(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 4: ", err)
	} else {
		p.Age = v
	}
	return nil
}

func (p *User) ReadField5(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 5: ", err)
	} else {
		temp := UserRole(v)
		p.Role = temp
	}
	return nil
}

func (p *User) ReadField6(ctx context.Context, iprot thrift.TProtocol) error {
	p.Details = &UserDetails{}
	if err := p.Details.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Details), err)
	}
	return nil
}

func (p *User) ReadField7(ctx context.Context, iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin(ctx)
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]string, 0, size)
	p.Tags = tSlice
	for i := 0; i < size; i++ {
		var _elem3 string
		if v, err := iprot.ReadString(ctx); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_elem3 = v
		}
		p.Tags = append(p.Tags, _elem3)
	}
	if err := iprot.ReadListEnd(ctx); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *User) ReadField8(ctx context.Context, iprot thrift.TProtocol) error {
	_, _, size, err := iprot.ReadMapBegin(ctx)
	if err != nil {
		return thrift.PrependError("error reading map begin: ", err)
	}
	tMap := make(map[string]string, size)
	p.Attributes = tMap
	for i := 0; i < size; i++ {
		var _key4 string
		if v, err := iprot.ReadString(ctx); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_key4 = v
		}
		var _val5 string
		if v, err := iprot.ReadString(ctx); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_val5 = v
		}
		p.Attributes[_key4] = _val5
	}
	if err := iprot.ReadMapEnd(ctx); err != nil {
		return thrift.PrependError("error reading map end: ", err)
	}
	return nil
}

func (p *User) ReadField9(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBool(ctx); err != nil {
		return thrift.PrependError("error reading field 9: ", err)
	} else {
		p.IsActive = &v
	}
	return nil
}

func (p *User) ReadField10(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadDouble(ctx); err != nil {
		return thrift.PrependError("error reading field 10: ", err)
	} else {
		p.Balance = &v
	}
	return nil
}

func (p *User) ReadField11(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(ctx); err != nil {
		return thrift.PrependError("error reading field 11: ", err)
	} else {
		p.CreatedAt = &v
	}
	return nil
}

func (p *User) ReadField12(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBinary(ctx); err != nil {
		return thrift.PrependError("error reading field 12: ", err)
	} else {
		p.Avatar = v
	}
	return nil
}

func (p *User) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "User"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil { return err }
		if err := p.writeField2(ctx, oprot); err != nil { return err }
		if err := p.writeField3(ctx, oprot); err != nil { return err }
		if err := p.writeField4(ctx, oprot); err != nil { return err }
		if err := p.writeField5(ctx, oprot); err != nil { return err }
		if err := p.writeField6(ctx, oprot); err != nil { return err }
		if err := p.writeField7(ctx, oprot); err != nil { return err }
		if err := p.writeField8(ctx, oprot); err != nil { return err }
		if err := p.writeField9(ctx, oprot); err != nil { return err }
		if err := p.writeField10(ctx, oprot); err != nil { return err }
		if err := p.writeField11(ctx, oprot); err != nil { return err }
		if err := p.writeField12(ctx, oprot); err != nil { return err }
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *User) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "id", thrift.I64, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:id: ", p), err)
	}
	if err := oprot.WriteI64(ctx, int64(p.ID)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.id (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:id: ", p), err)
	}
	return err
}

func (p *User) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "name", thrift.STRING, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:name: ", p), err)
	}
	if err := oprot.WriteString(ctx, string(p.Name)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.name (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:name: ", p), err)
	}
	return err
}

func (p *User) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "email", thrift.STRING, 3); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:email: ", p), err)
	}
	if err := oprot.WriteString(ctx, string(p.Email)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.email (3) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 3:email: ", p), err)
	}
	return err
}

func (p *User) writeField4(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "age", thrift.I32, 4); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:age: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.Age)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.age (4) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 4:age: ", p), err)
	}
	return err
}

func (p *User) writeField5(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "role", thrift.I32, 5); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 5:role: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.Role)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.role (5) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 5:role: ", p), err)
	}
	return err
}

func (p *User) writeField6(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetDetails() {
		if err := oprot.WriteFieldBegin(ctx, "details", thrift.STRUCT, 6); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 6:details: ", p), err)
		}
		if err := p.Details.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Details), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 6:details: ", p), err)
		}
	}
	return err
}

func (p *User) writeField7(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "tags", thrift.LIST, 7); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 7:tags: ", p), err)
	}
	if err := oprot.WriteListBegin(ctx, thrift.STRING, len(p.Tags)); err != nil {
		return thrift.PrependError("error writing list begin: ", err)
	}
	for _, v := range p.Tags {
		if err := oprot.WriteString(ctx, string(v)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
		}
	}
	if err := oprot.WriteListEnd(ctx); err != nil {
		return thrift.PrependError("error writing list end: ", err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 7:tags: ", p), err)
	}
	return err
}

func (p *User) writeField8(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "attributes", thrift.MAP, 8); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 8:attributes: ", p), err)
	}
	if err := oprot.WriteMapBegin(ctx, thrift.STRING, thrift.STRING, len(p.Attributes)); err != nil {
		return thrift.PrependError("error writing map begin: ", err)
	}
	for k, v := range p.Attributes {
		if err := oprot.WriteString(ctx, string(k)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
		}
		if err := oprot.WriteString(ctx, string(v)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
		}
	}
	if err := oprot.WriteMapEnd(ctx); err != nil {
		return thrift.PrependError("error writing map end: ", err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 8:attributes: ", p), err)
	}
	return err
}

func (p *User) writeField9(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetIsActive() {
		if err := oprot.WriteFieldBegin(ctx, "isActive", thrift.BOOL, 9); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 9:isActive: ", p), err)
		}
		if err := oprot.WriteBool(ctx, bool(*p.IsActive)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.isActive (9) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 9:isActive: ", p), err)
		}
	}
	return err
}

func (p *User) writeField10(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetBalance() {
		if err := oprot.WriteFieldBegin(ctx, "balance", thrift.DOUBLE, 10); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 10:balance: ", p), err)
		}
		if err := oprot.WriteDouble(ctx, float64(*p.Balance)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.balance (10) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 10:balance: ", p), err)
		}
	}
	return err
}

func (p *User) writeField11(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetCreatedAt() {
		if err := oprot.WriteFieldBegin(ctx, "createdAt", thrift.I64, 11); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 11:createdAt: ", p), err)
		}
		if err := oprot.WriteI64(ctx, int64(*p.CreatedAt)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.createdAt (11) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 11:createdAt: ", p), err)
		}
	}
	return err
}

func (p *User) writeField12(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "avatar", thrift.STRING, 12); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 12:avatar: ", p), err)
	}
	if err := oprot.WriteBinary(ctx, p.Avatar); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.avatar (12) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 12:avatar: ", p), err)
	}
	return err
}

func (p *User) Equals(other *User) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if p.ID != other.ID { return false }
	if p.Name != other.Name { return false }
	if p.Email != other.Email { return false }
	if p.Age != other.Age { return false }
	if p.Role != other.Role { return false }
	if !p.Details.Equals(other.Details) { return false }
	if len(p.Tags) != len(other.Tags) { return false }
	for i, _tgt := range p.Tags {
		_src6 := other.Tags[i]
		if _tgt != _src6 { return false }
	}
	if len(p.Attributes) != len(other.Attributes) { return false }
	for k, _tgt := range p.Attributes {
		_src7 := other.Attributes[k]
		if _tgt != _src7 { return false }
	}
	if p.IsActive != other.IsActive {
		if p.IsActive == nil || other.IsActive == nil {
			return false
		}
		if (*p.IsActive) != (*other.IsActive) { return false }
	}
	if p.Balance != other.Balance {
		if p.Balance == nil || other.Balance == nil {
			return false
		}
		if (*p.Balance) != (*other.Balance) { return false }
	}
	if p.CreatedAt != other.CreatedAt {
		if p.CreatedAt == nil || other.CreatedAt == nil {
			return false
		}
		if (*p.CreatedAt) != (*other.CreatedAt) { return false }
	}
	if bytes.Compare(p.Avatar, other.Avatar) != 0 { return false }
	return true
}

func (p *User) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("User(%+v)", *p)
}

func (p *User) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type: "*user_service.User",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*User)(nil)

func (p *User) Validate() error {
	return nil
}

// Attributes:
//  - ServerId
//  - ClientData
//  - User
// 
type EchoResponse struct {
	ServerId int64 `thrift:"serverId,1" db:"serverId" json:"serverId"`
	ClientData []byte `thrift:"clientData,2" db:"clientData" json:"clientData"`
	User *User `thrift:"user,3" db:"user" json:"user"`
}

func NewEchoResponse() *EchoResponse {
	return &EchoResponse{}
}



func (p *EchoResponse) GetServerId() int64 {
	return p.ServerId
}



func (p *EchoResponse) GetClientData() []byte {
	return p.ClientData
}

var EchoResponse_User_DEFAULT *User

func (p *EchoResponse) GetUser() *User {
	if !p.IsSetUser() {
		return EchoResponse_User_DEFAULT
	}
	return p.User
}

func (p *EchoResponse) IsSetUser() bool {
	return p.User != nil
}

func (p *EchoResponse) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}


	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I64 {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 3:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField3(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *EchoResponse) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.ServerId = v
	}
	return nil
}

func (p *EchoResponse) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBinary(ctx); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.ClientData = v
	}
	return nil
}

func (p *EchoResponse) ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
	p.User = &User{
		Role: 2,
		Tags: []string{
		},
		Attributes: map[string]string{
		},
	}
	if err := p.User.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.User), err)
	}
	return nil
}

func (p *EchoResponse) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "EchoResponse"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil { return err }
		if err := p.writeField2(ctx, oprot); err != nil { return err }
		if err := p.writeField3(ctx, oprot); err != nil { return err }
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *EchoResponse) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "serverId", thrift.I64, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:serverId: ", p), err)
	}
	if err := oprot.WriteI64(ctx, int64(p.ServerId)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.serverId (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:serverId: ", p), err)
	}
	return err
}

func (p *EchoResponse) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "clientData", thrift.STRING, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:clientData: ", p), err)
	}
	if err := oprot.WriteBinary(ctx, p.ClientData); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.clientData (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:clientData: ", p), err)
	}
	return err
}

func (p *EchoResponse) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "user", thrift.STRUCT, 3); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:user: ", p), err)
	}
	if err := p.User.Write(ctx, oprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.User), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 3:user: ", p), err)
	}
	return err
}

func (p *EchoResponse) Equals(other *EchoResponse) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if p.ServerId != other.ServerId { return false }
	if bytes.Compare(p.ClientData, other.ClientData) != 0 { return false }
	if !p.User.Equals(other.User) { return false }
	return true
}

func (p *EchoResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EchoResponse(%+v)", *p)
}

func (p *EchoResponse) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type: "*user_service.EchoResponse",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*EchoResponse)(nil)

func (p *EchoResponse) Validate() error {
	return nil
}

type UserService interface {
	// Parameters:
	//  - ClientData
	//  - User
	// 
	EchoData(ctx context.Context, clientData []byte, user *User) (_r *EchoResponse, _err error)
}

type UserServiceClient struct {
	c thrift.TClient
	meta thrift.ResponseMeta
}

func NewUserServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *UserServiceClient {
	return &UserServiceClient{
		c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
	}
}

func NewUserServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *UserServiceClient {
	return &UserServiceClient{
		c: thrift.NewTStandardClient(iprot, oprot),
	}
}

func NewUserServiceClient(c thrift.TClient) *UserServiceClient {
	return &UserServiceClient{
		c: c,
	}
}

func (p *UserServiceClient) Client_() thrift.TClient {
	return p.c
}

func (p *UserServiceClient) LastResponseMeta_() thrift.ResponseMeta {
	return p.meta
}

func (p *UserServiceClient) SetLastResponseMeta_(meta thrift.ResponseMeta) {
	p.meta = meta
}

// Parameters:
//  - ClientData
//  - User
// 
func (p *UserServiceClient) EchoData(ctx context.Context, clientData []byte, user *User) (_r *EchoResponse, _err error) {
	var _args8 UserServiceEchoDataArgs
	_args8.ClientData = clientData
	_args8.User = user
	var _result10 UserServiceEchoDataResult
	var _meta9 thrift.ResponseMeta
	_meta9, _err = p.Client_().Call(ctx, "echoData", &_args8, &_result10)
	p.SetLastResponseMeta_(_meta9)
	if _err != nil {
		return
	}
	if _ret11 := _result10.GetSuccess(); _ret11 != nil {
		return _ret11, nil
	}
	return nil, thrift.NewTApplicationException(thrift.MISSING_RESULT, "echoData failed: unknown result")
}

type UserServiceProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler UserService
}

func (p *UserServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *UserServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *UserServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewUserServiceProcessor(handler UserService) *UserServiceProcessor {

	self12 := &UserServiceProcessor{handler:handler, processorMap:make(map[string]thrift.TProcessorFunction)}
	self12.processorMap["echoData"] = &userServiceProcessorEchoData{handler:handler}
	return self12
}

func (p *UserServiceProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err2 := iprot.ReadMessageBegin(ctx)
	if err2 != nil { return false, thrift.WrapTException(err2) }
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(ctx, seqId, iprot, oprot)
	}
	iprot.Skip(ctx, thrift.STRUCT)
	iprot.ReadMessageEnd(ctx)
	x13 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function " + name)
	oprot.WriteMessageBegin(ctx, name, thrift.EXCEPTION, seqId)
	x13.Write(ctx, oprot)
	oprot.WriteMessageEnd(ctx)
	oprot.Flush(ctx)
	return false, x13
}

type userServiceProcessorEchoData struct {
	handler UserService
}

func (p *userServiceProcessorEchoData) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	var _write_err14 thrift.TException
	args := UserServiceEchoDataArgs{}
	if err2 := args.Read(ctx, iprot); err2 != nil {
		iprot.ReadMessageEnd(ctx)
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err2.Error())
		oprot.WriteMessageBegin(ctx, "echoData", thrift.EXCEPTION, seqId)
		x.Write(ctx, oprot)
		oprot.WriteMessageEnd(ctx)
		oprot.Flush(ctx)
		return false, thrift.WrapTException(err2)
	}
	iprot.ReadMessageEnd(ctx)

	tickerCancel := func() {}
	// Start a goroutine to do server side connectivity check.
	if thrift.ServerConnectivityCheckInterval > 0 {
		var cancel context.CancelCauseFunc
		ctx, cancel = context.WithCancelCause(ctx)
		defer cancel(nil)
		var tickerCtx context.Context
		tickerCtx, tickerCancel = context.WithCancel(context.Background())
		defer tickerCancel()
		go func(ctx context.Context, cancel context.CancelCauseFunc) {
			ticker := time.NewTicker(thrift.ServerConnectivityCheckInterval)
			defer ticker.Stop()
			for {
				select {
				case <-ctx.Done():
					return
				case <-ticker.C:
					if !iprot.Transport().IsOpen() {
						cancel(thrift.ErrAbandonRequest)
						return
					}
				}
			}
		}(tickerCtx, cancel)
	}

	result := UserServiceEchoDataResult{}
	if retval, err2 := p.handler.EchoData(ctx, args.ClientData, args.User); err2 != nil {
		tickerCancel()
		err = thrift.WrapTException(err2)
		if errors.Is(err2, thrift.ErrAbandonRequest) {
			return false, &thrift.ProcessorError{
				WriteError:    thrift.WrapTException(err2),
				EndpointError: err,
			}
		}
		if errors.Is(err2, context.Canceled) {
			if err3 := context.Cause(ctx); errors.Is(err3, thrift.ErrAbandonRequest) {
				return false, &thrift.ProcessorError{
					WriteError:    thrift.WrapTException(err3),
					EndpointError: err,
				}
			}
		}
		_exc15 := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing echoData: " + err2.Error())
		if err2 := oprot.WriteMessageBegin(ctx, "echoData", thrift.EXCEPTION, seqId); err2 != nil {
			_write_err14 = thrift.WrapTException(err2)
		}
		if err2 := _exc15.Write(ctx, oprot); _write_err14 == nil && err2 != nil {
			_write_err14 = thrift.WrapTException(err2)
		}
		if err2 := oprot.WriteMessageEnd(ctx); _write_err14 == nil && err2 != nil {
			_write_err14 = thrift.WrapTException(err2)
		}
		if err2 := oprot.Flush(ctx); _write_err14 == nil && err2 != nil {
			_write_err14 = thrift.WrapTException(err2)
		}
		if _write_err14 != nil {
			return false, &thrift.ProcessorError{
				WriteError:    _write_err14,
				EndpointError: err,
			}
		}
		return true, err
	} else {
		result.Success = retval
	}
	tickerCancel()
	if err2 := oprot.WriteMessageBegin(ctx, "echoData", thrift.REPLY, seqId); err2 != nil {
		_write_err14 = thrift.WrapTException(err2)
	}
	if err2 := result.Write(ctx, oprot); _write_err14 == nil && err2 != nil {
		_write_err14 = thrift.WrapTException(err2)
	}
	if err2 := oprot.WriteMessageEnd(ctx); _write_err14 == nil && err2 != nil {
		_write_err14 = thrift.WrapTException(err2)
	}
	if err2 := oprot.Flush(ctx); _write_err14 == nil && err2 != nil {
		_write_err14 = thrift.WrapTException(err2)
	}
	if _write_err14 != nil {
		return false, &thrift.ProcessorError{
			WriteError:    _write_err14,
			EndpointError: err,
		}
	}
	return true, err
}


// HELPER FUNCTIONS AND STRUCTURES

// Attributes:
//  - ClientData
//  - User
// 
type UserServiceEchoDataArgs struct {
	ClientData []byte `thrift:"clientData,1" db:"clientData" json:"clientData"`
	User *User `thrift:"user,2" db:"user" json:"user"`
}

func NewUserServiceEchoDataArgs() *UserServiceEchoDataArgs {
	return &UserServiceEchoDataArgs{}
}



func (p *UserServiceEchoDataArgs) GetClientData() []byte {
	return p.ClientData
}

var UserServiceEchoDataArgs_User_DEFAULT *User

func (p *UserServiceEchoDataArgs) GetUser() *User {
	if !p.IsSetUser() {
		return UserServiceEchoDataArgs_User_DEFAULT
	}
	return p.User
}

func (p *UserServiceEchoDataArgs) IsSetUser() bool {
	return p.User != nil
}

func (p *UserServiceEchoDataArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}


	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *UserServiceEchoDataArgs) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBinary(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.ClientData = v
	}
	return nil
}

func (p *UserServiceEchoDataArgs) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	p.User = &User{
		Role: 2,
		Tags: []string{
		},
		Attributes: map[string]string{
		},
	}
	if err := p.User.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.User), err)
	}
	return nil
}

func (p *UserServiceEchoDataArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "echoData_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil { return err }
		if err := p.writeField2(ctx, oprot); err != nil { return err }
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *UserServiceEchoDataArgs) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "clientData", thrift.STRING, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:clientData: ", p), err)
	}
	if err := oprot.WriteBinary(ctx, p.ClientData); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.clientData (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:clientData: ", p), err)
	}
	return err
}

func (p *UserServiceEchoDataArgs) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "user", thrift.STRUCT, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:user: ", p), err)
	}
	if err := p.User.Write(ctx, oprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.User), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:user: ", p), err)
	}
	return err
}

func (p *UserServiceEchoDataArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceEchoDataArgs(%+v)", *p)
}

func (p *UserServiceEchoDataArgs) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type: "*user_service.UserServiceEchoDataArgs",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*UserServiceEchoDataArgs)(nil)

// Attributes:
//  - Success
// 
type UserServiceEchoDataResult struct {
	Success *EchoResponse `thrift:"success,0" db:"success" json:"success,omitempty"`
}

func NewUserServiceEchoDataResult() *UserServiceEchoDataResult {
	return &UserServiceEchoDataResult{}
}

var UserServiceEchoDataResult_Success_DEFAULT *EchoResponse

func (p *UserServiceEchoDataResult) GetSuccess() *EchoResponse {
	if !p.IsSetSuccess() {
		return UserServiceEchoDataResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UserServiceEchoDataResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceEchoDataResult) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}


	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField0(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *UserServiceEchoDataResult) ReadField0(ctx context.Context, iprot thrift.TProtocol) error {
	p.Success = &EchoResponse{}
	if err := p.Success.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Success), err)
	}
	return nil
}

func (p *UserServiceEchoDataResult) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "echoData_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField0(ctx, oprot); err != nil { return err }
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *UserServiceEchoDataResult) writeField0(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin(ctx, "success", thrift.STRUCT, 0); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err)
		}
		if err := p.Success.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Success), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err)
		}
	}
	return err
}

func (p *UserServiceEchoDataResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceEchoDataResult(%+v)", *p)
}

func (p *UserServiceEchoDataResult) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type: "*user_service.UserServiceEchoDataResult",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*UserServiceEchoDataResult)(nil)


