// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"aboveThriftRPC/internal/biz"
	"aboveThriftRPC/internal/conf"
	"aboveThriftRPC/internal/data"
	"aboveThriftRPC/internal/server"
	"aboveThriftRPC/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData)
	userUsecase := biz.NewUserUsecase(userRepo)
	userService := service.NewThriftUserService(userUsecase)
	thriftServer, err := server.NewThriftServer(confServer, userService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := newApp(logger, thriftServer)
	return app, func() {
		cleanup()
	}, nil
}
